#69231229 Configure data flow
hezzie/OddWeather pull request #1
Opened 2019-10-21 18:34 UTC by hezzie

#### What does this PR do?
This PR configures the flow of data
#### Description of Task to be completed?
- Consume the open weather API
- Create a Form component.
- Create functions to handle the transfer of data from Form(child) component to App(parent).
#### How should this be manually tested?
- Clone this repo
- cd . into ch-data-flow-169231229 branch
- install the dependencies (npm install)
- Start the app (npm, start)
#### What are the relevant pivotal tracker stories?
[#169231229](https://www.pivotaltracker.com/n/projects/2406895/stories/169231229)

2019-10-22 06:21 UTC, NiyoEric commented
I have 2 feedback for you
 1. Hide API **APP_KEY** in your **.env** and use process.env to access it.
 2. Can you display the city name as our form placeholder from the state so that users understand why by default we display Kigali?

2019-10-22 10:08 UTC, kipropbrian requested changes
Left some change requests and questions. Also
The PR description format is not looking very good. Check here for how to style it.
https://github.com/andela/engineering-playbook/tree/c74e0b42578fcf45d76b91e43b85d5159821b7ea/5.%20Developing/Conventions

There should be a PR for the PR_template.md this will pre-format your PR's.

2019-10-22 10:08 UTC, kipropbrian commented on src/App.js
> +      city: "kigali",
This should not be hard coded

2019-10-22 10:08 UTC, kipropbrian commented on src/App.js
> +      const url = `http://api.openweathermap.org/data/2.5/forecast?q=${city}&APPID=${Key}`;
The URL should also not be hardcoded

2019-10-22 10:08 UTC, kipropbrian commented on src/components/Form.js
> +class Form extends Component {
Is this a general form? If not the name should reflect what exactly it is doing.

2019-10-22 12:32 UTC, hezzie commented on src/App.js
> +      city: "kigali",
Okey Let me work on it.

2019-10-23 14:51 UTC, kiproping commented on src/App.js
> +          state={this.state}
Since you just require the city, why not `city={this.state.city}`

2019-10-23 14:52 UTC, kipropbrian commented on src/App.js
> +          state={this.state}
Since you just need the city from the state, just do `city={this.state.city}`

2019-10-23 17:18 UTC, victorkarangwa reviewed
Good to go!

2019-10-24 10:24 UTC, WillyBoris approved these changes

2019-10-24 10:30 UTC, NiyoEric approved these changes

2019-10-24 10:38 UTC, victorkarangwa approved these changes

2019-10-24 10:50 UTC, WillyBoris approved these changes

2019-10-24 11:48 UTC, kiproping commented on src/components/Form.js
> +    const city = this.props.city;
There is no props called city.

2019-10-24 15:49 UTC, WillyBoris approved these changes

2019-10-24 15:49 UTC, merged