#169230797 Search form and Popular Cities
hezzie/OddWeather pull request #2
Opened 2019-10-22 20:31 UTC by WillyBoris

#### What does this PR do?
 Make Search form 
#### Description of Task to be completed?
- Add search fields and search button
- Add popular cities that have been recently searched
#### How should this be manually tested?
- Clone this repo
- cd . into ft-search-form-169230797  branch
- install the dependencies (npm install)
- Start the app
#### Any background context you want to provide?
N/A
#### What are the relevant pivotal tracker stories?
[#169230797](https://www.pivotaltracker.com/story/show/169230797)
#### Screenshot?
![image](https://user-images.githubusercontent.com/56690476/67329798-a7398e80-f51b-11e9-8cde-90be4e325e00.png)

2019-10-23 10:57 UTC, kipropbrian commented
There is nothing here.

2019-10-23 11:46 UTC, WillyBoris commented
> There is nothing here.

> I corrected it, you can see the changes

2019-10-23 11:58 UTC, victorkarangwa commented on src/App.js
> +      recentCities:['kigali', 'dodoma', 'nairobi'],
Let's just remove these hardcoded data

2019-10-23 12:02 UTC, victorkarangwa reviewed
Get rid of hardcoded data

2019-10-23 12:03 UTC, NiyoEric requested changes

2019-10-23 12:03 UTC, NiyoEric commented on src/components/Form.js
> +            this.props.state.recentCities.map((item, index) => {
can use es6 to destructure *recentCities* from the state?

2019-10-23 18:35 UTC, ivymwende reviewed
Nice Work! However please add font styling to the form to make it more visually appealing.

2019-10-24 05:51 UTC, NiyoEric approved these changes

2019-10-24 08:14 UTC, WillyBoris commented
> Nice Work! However please add font styling to the form to make it more visually appealing.

>I have added the font you asked for

2019-10-24 08:24 UTC, victorkarangwa approved these changes

2019-10-24 10:24 UTC, hezzie approved these changes

2019-10-24 10:39 UTC, victorkarangwa approved these changes

2019-10-24 18:08 UTC, merged